# Site settings
title: German Ostaszynski
description: Projects and experience
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: German Ostaszynski
user_description: I'm a Web Developer and Photographer from Costa Rica, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been developing my photography skills. During the day you can find me working is a project and sales manager at Corporacion Watersonn.
photography_description: I have always been interested and passionate in photography. Currently I am improving my skils at Universad Veritas in Costa Rica.
user_title: Web Developer and Photographer
email: german92@gmail.com
# twitter_username: lorem_ipsum
instagram_username: osgerman
facebook_username: osgerman
linkedin_username: german92
github_username:  german92
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
